# Change these first
owner: AneFaiz # Your GitHub organization or username, where this repository lives
repo: stats # The name of this repository

sites:
  - name: AneFaiz Studio
    url: https://stats.anefaiz.biz.id/
  - name: Zufty Smp
    url: https://site.zuftysmp.online/
  - name: Titas IT Solution
    url: https://titasitsolution.com/
  - name: Ramzi Store
    url: https://ramzistore.biz.id/
  - name: target 1
    url: https://mevichost.com/
  - name: target 2
    url: https://dash.mevichost.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: stats.anefaiz.biz.id
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: AneFaiz Studio
  introTitle: "**Status Panel**"
  introMessage: Status Di Update Secara Real Time.
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
